name: buzzmatch_v5
description: A platform that connects content creators with brands for advertising campaigns.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.1.1  # Ensure you're using the latest version
  
  flutter_localizations:
    sdk: flutter

  # GetX for state management and navigation
  get: ^4.6.5
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.9
  
  # Authentication
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^5.0.0
  
  # UI
  cupertino_icons: ^1.0.5
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  flutter_spinkit: ^5.2.0
  lottie: ^2.7.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  
  # Utilities
  intl: ^0.19.0
  logger: ^2.0.2
  url_launcher: ^6.2.2
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  permission_handler: ^11.0.1
  connectivity_plus: ^5.0.2
  
  # Payments
  flutter_stripe: ^9.5.0+1
  flutter_paypal: ^0.2.0
  
  # Animations
  flutter_animate: ^4.3.0
  
  # Others
  uuid: ^4.2.1
  timeago: ^3.6.0
  country_picker: ^2.0.22
  flutter_native_splash: ^2.3.8
  flutter_launcher_icons: ^0.13.1
  http: ^1.1.2
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700

flutter_native_splash:
  color: "#FDF5D9"
  image: assets/images/logo.png
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21